name: Update README
on:
  push:
    branches:
      - main
  schedule:
    # Once a day at 12 PM UTC
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://django-news.com/issues.rss
          readme-section: news
          max: 5
          template: "* [{{ title }}]({{ link }})"

      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://feeds.simplecast.com/WpQaX_cs
          readme-section: chat
          max: 5
          template: "* [{{ title }}]({{ link }})"
