name: Update README
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://django-news.com/issues.rss,https://feeds.simplecast.com/WpQaX_cs,https://wsvincent.com/feed.xml"
          max_post_count: 5
          readme_path: ./README.md
          template: "* [$title]($url)"
